### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by kathryn0628**
Text and font.

### CODE REVIEW

**Comment by bdb67** [comment]
Update text and font

**Comment by kathryn0628** [comment]
CSS still needs some edits from my end. I'll send one more push tonight. I
didn't grab all the embedded p's and h1s to turn them the appropriate
color. It's a quick fix- I'll do it before the big game. (golden state!)

On Tue, Jun 16, 2015 at 8:42 AM, Brandon Bass notifications@github.com
wrote:

> Merged #4 https://github.com/bdb67/mysunbuddy/pull/4.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bdb67/mysunbuddy/pull/4#event-332047785.

## 

Kathryn Wright
Yale University 2013
University of Pittsburgh 2011

**Comment by bdb67** [comment]
Great looking forward to it!

**Comment by bdb67** [comment]
additionally if you could save the solar panel image in a less quality
format i think that would help dramatically.  you can put it in the
static/img file and serve it directly.  i can take care of this as well,
but if you're hacking it tonight it may be a good step.

**Comment by kathryn0628** [comment]
Sure thing. It's from Wikimedia so there's a bundle o' options for size

**Pull request merged**
