### PR TITLE
Adjusted the CSS

### PR DESCRIPTION
**Pull request by kathryn0628**
Still in search of a decent header image. Need to find panels in a shade of blue. The image before was too busy to put text on top of.

### CODE REVIEW

**Comment by bdb67** [comment]
Hey Kathryn,

I see what you were going for, but the alignment on the page was pretty
badly off when I merged and pushed it, I'd guess maybe some of the icon
sizing threw something off, but I don't have time tonight to debug.  I
absolutely am thrilled to have you working on the code, but I won't be able
to test all of your code pushes, and I want to be able to trust that
merging it into master won't throw anything off.   I know that you've had
some time to download python and the like.  Before I push any of my code to
master, I deploy it on my machine at localhost to ensure that it is
deployment-ready code, have you been doing this as well?  If so I'm not
really sure how to QC this type of thing.  In the mean time I've made some
of the changes you had suggested in your pull request.

Best,
Brandon

On Sun, May 31, 2015 at 8:19 PM, kathryn0628 notifications@github.com
wrote:

> Still in search of a decent header image. Need to find panels in a shade
> 
> ## of blue. The image before was too busy to put text on top of.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/bdb67/mysunbuddy/pull/2
> Commit Summary
> - Update index.html
> - Update creative.css
> 
> File Changes
> - _M_ static/css/creative.css
>   https://github.com/bdb67/mysunbuddy/pull/2/files#diff-0 (100)
> - _M_ templates/index.html
>   https://github.com/bdb67/mysunbuddy/pull/2/files#diff-1 (161)
> 
> Patch Links:
> - https://github.com/bdb67/mysunbuddy/pull/2.patch
> - https://github.com/bdb67/mysunbuddy/pull/2.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bdb67/mysunbuddy/pull/2.

## 

Brandon D. Bass, M.Eng., EIT
845.709.9563

**Comment by kathryn0628** [comment]
I run everything through browser view on Dreamweaver- it looked OK there. I
originally sized the icons for a 3 columns instead of a 4 when I did an
original pass at the front-end html and CSS a while back - I imagine that
is what is causing the issue. I can look at that section again tomorrow
before you spend time checking it, and figure out a better size in photoshop

Kathryn

On Sun, May 31, 2015 at 8:57 PM, Brandon Bass notifications@github.com
wrote:

> Hey Kathryn,
> 
> I see what you were going for, but the alignment on the page was pretty
> badly off when I merged and pushed it, I'd guess maybe some of the icon
> sizing threw something off, but I don't have time tonight to debug. I
> absolutely am thrilled to have you working on the code, but I won't be able
> to test all of your code pushes, and I want to be able to trust that
> merging it into master won't throw anything off. I know that you've had
> some time to download python and the like. Before I push any of my code to
> master, I deploy it on my machine at localhost to ensure that it is
> deployment-ready code, have you been doing this as well? If so I'm not
> really sure how to QC this type of thing. In the mean time I've made some
> of the changes you had suggested in your pull request.
> 
> Best,
> Brandon
> 
> On Sun, May 31, 2015 at 8:19 PM, kathryn0628 notifications@github.com
> wrote:
> 
> > Still in search of a decent header image. Need to find panels in a shade
> > 
> > ## of blue. The image before was too busy to put text on top of.
> > 
> > You can view, comment on, or merge this pull request online at:
> > 
> > https://github.com/bdb67/mysunbuddy/pull/2
> > Commit Summary
> > - Update index.html
> > - Update creative.css
> > 
> > File Changes
> > - _M_ static/css/creative.css
> >   https://github.com/bdb67/mysunbuddy/pull/2/files#diff-0 (100)
> > - _M_ templates/index.html
> >   https://github.com/bdb67/mysunbuddy/pull/2/files#diff-1 (161)
> > 
> > Patch Links:
> > - https://github.com/bdb67/mysunbuddy/pull/2.patch
> > - https://github.com/bdb67/mysunbuddy/pull/2.diff
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/bdb67/mysunbuddy/pull/2.
> 
> ## 
> 
> Brandon D. Bass, M.Eng., EIT
> 845.709.9563
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bdb67/mysunbuddy/pull/2#issuecomment-107271329.

## 

Kathryn Wright
Yale University 2013
University of Pittsburgh 2011

**Comment by bdb67** [comment]
Ah that makes sense. Fantastic no rush, the interest thing is up and thats
a good start!

**Comment by kathryn0628** [comment]
Truth - baby steps. I'll continue working on it tomorrow. But here's how it
looks in Codepen and on my screen, click the pen at the top:

https://gist.github.com/kathryn0628/73982cd94c73a710b3d9

So maybe I'm doing something wrong. It's the icon section that's misaligned
for you?

On Sun, May 31, 2015 at 9:56 PM, Brandon Bass notifications@github.com
wrote:

> Ah that makes sense. Fantastic no rush, the interest thing is up and thats
> a good start!
> 
> On May 31, 2015 9:44 PM, "kathryn0628" notifications@github.com wrote:
> 
> > I run everything through browser view on Dreamweaver- it looked OK
> > there. I
> > originally sized the icons for a 3 columns instead of a 4 when I did an
> > original pass at the front-end html and CSS a while back - I imagine that
> > is what is causing the issue. I can look at that section again tomorrow
> > before you spend time checking it, and figure out a better size in
> > photoshop
> > 
> > Kathryn
> > 
> > On Sun, May 31, 2015 at 8:57 PM, Brandon Bass notifications@github.com
> > wrote:
> > 
> > > Hey Kathryn,
> > > 
> > > I see what you were going for, but the alignment on the page was pretty
> > > badly off when I merged and pushed it, I'd guess maybe some of the icon
> > > sizing threw something off, but I don't have time tonight to debug. I
> > > absolutely am thrilled to have you working on the code, but I won't be
> > > able
> > > to test all of your code pushes, and I want to be able to trust that
> > > merging it into master won't throw anything off. I know that you've had
> > > some time to download python and the like. Before I push any of my code
> > > to
> > > master, I deploy it on my machine at localhost to ensure that it is
> > > deployment-ready code, have you been doing this as well? If so I'm not
> > > really sure how to QC this type of thing. In the mean time I've made
> > > some
> > > of the changes you had suggested in your pull request.
> > > 
> > > Best,
> > > Brandon
> > > 
> > > On Sun, May 31, 2015 at 8:19 PM, kathryn0628 <notifications@github.com
> > > 
> > > wrote:
> > > 
> > > > Still in search of a decent header image. Need to find panels in a
> > > > shade
> > > > 
> > > > ## of blue. The image before was too busy to put text on top of.
> > > > 
> > > > You can view, comment on, or merge this pull request online at:
> > > > 
> > > > https://github.com/bdb67/mysunbuddy/pull/2
> > > > Commit Summary
> > > > - Update index.html
> > > > - Update creative.css
> > > > 
> > > > File Changes
> > > > - _M_ static/css/creative.css
> > > >   https://github.com/bdb67/mysunbuddy/pull/2/files#diff-0 (100)
> > > > - _M_ templates/index.html
> > > >   https://github.com/bdb67/mysunbuddy/pull/2/files#diff-1 (161)
> > > > 
> > > > Patch Links:
> > > > - https://github.com/bdb67/mysunbuddy/pull/2.patch
> > > > - https://github.com/bdb67/mysunbuddy/pull/2.diff
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/bdb67/mysunbuddy/pull/2.
> > > 
> > > ## 
> > > 
> > > Brandon D. Bass, M.Eng., EIT
> > > 845.709.9563
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/bdb67/mysunbuddy/pull/2#issuecomment-107271329.
> > 
> > ## 
> > 
> > Kathryn Wright
> > Yale University 2013
> > University of Pittsburgh 2011
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/bdb67/mysunbuddy/pull/2#issuecomment-107278941.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bdb67/mysunbuddy/pull/2#issuecomment-107280556.

## 

Kathryn Wright
Yale University 2013
University of Pittsburgh 2011

**Comment by bdb67** [comment]
When you make the screen less than full size, the icon section starts to
get badly misaligned.  Nice use of code pen btw :)

**Pull request merged**
